name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.8.0
    - name: Build the Docker image
      run: docker buildx build --platform linux/arm64 network_backend/ -t network:latest
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.13.0
      with:
        file: Dockerfile
        platforms: linux/arm64,linux/amd64
        push: true
        tags: christianschwartz/network:latest
